export default {
    award: new URL('./award.png', import.meta.url).href,
    big_idea: new URL('./big-idea.png', import.meta.url).href,
    boy: new URL('./boy.png', import.meta.url).href,
    boom: new URL('./boom.png', import.meta.url).href,
    chain: new URL('./chain.png', import.meta.url).href,
    globe: new URL('./globe.png', import.meta.url).href,
    light_bulb: new URL('./light-bulb.png', import.meta.url).href,
    man: new URL('./man.png', import.meta.url).href,
    woman: new URL('./woman.png', import.meta.url).href,
    worker: new URL('./worker.png', import.meta.url).href,
    first: new URL('./first.png', import.meta.url).href,
    second: new URL('./second.png', import.meta.url).href,
    third: new URL('./third.png', import.meta.url).href,
    sponsor_liberty: new URL('./sponsor_liberty.png', import.meta.url).href,
    sponsor_liberty_pay: new URL('./sponsor_liberty_pay.png', import.meta.url)
        .href,
    sponsor_paybox: new URL('./sponsor_paybox.png', import.meta.url).href,
    sponsor_plus: new URL('./sponsor_plus.png', import.meta.url).href,
    sponsor_whisper: new URL('./sponsor_whisper.png', import.meta.url).href,
    sponsor_winwise: new URL('./sponsor_winwise.png', import.meta.url).href,
    security: new URL('./secure.png', import.meta.url).href,
    gdesigner: new URL('./gdesigner.png', import.meta.url).href,
    girl: new URL('./girl.png', import.meta.url).href,
    boy2: new URL('./boy2.png', import.meta.url).href,
    congrats: new URL('./congrats.png', import.meta.url).href,
    wink: new URL('./wink.png', import.meta.url).href,
};
